targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        options:
          auto_register: true
          # auto registers any class with a name matches the given pattern
          class_name_pattern:
            "Service$|Repository$|RepositoryImpl$|Bloc$|Cubit$|DataSource$|UseCase$|SubscriptionManager$|Notifier$"
            # auto registers any class inside a file with a
          # name matches the given pattern
          file_name_pattern: "_service$|_repository$|_repository_impl$|_bloc$|_cubit$|_data_source$|_use_case$|_subscription_manager$|_notifier$"
