name: marvel_knowledge_compendium
description: A Flutter project letting you find information related to Marvel universe and it's heroes.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  alphabet_list_scroll_view: ^2.0.0
  auto_route: ^4.2.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.1.1+1
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  mocktail: ^0.3.0
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.0.15

dev_dependencies:
  auto_route_generator: ^4.2.0
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  injectable_generator:
  json_serializable: ^6.2.0
  network_image_mock: ^2.1.1

flutter:
  uses-material-design: true

  assets:
    - lib/res/images/
